import { Check, FileCheck2, ShieldCheck } from 'lucide-react';
import styles from './business-health-tax-section.module.css';

const companyPoints = ['Debe vincularse a la política retributiva o de personal.', 'Conviene validarlo con la asesoría fiscal y laboral.'];

export function BusinessHealthTaxSection() {
  return <section className={styles.section} aria-labelledby="business-health-tax-title"><div className={`container-shell ${styles.shell}`}><div className={styles.panel}><div className={styles.taxMain}><p className={styles.eyebrow}><ShieldCheck aria-hidden="true" />FISCALIDAD EXPLICADA CON CLARIDAD</p><h2 id="business-health-tax-title">Fiscalidad del seguro de salud para empresas</h2><p className={styles.intro}>En territorio común, parte de la prima pagada por la empresa puede quedar exenta de IRPF para el trabajador cuando se cumplen los requisitos legales.</p><div className={styles.limits}><div><strong>500 €</strong><span>de prima anual por persona</span></div><div><strong>1.500 €</strong><span>de prima anual por persona con discapacidad</span></div></div><p className={styles.familyNote}>La cobertura puede alcanzar al trabajador, a su cónyuge y a sus descendientes, siempre que se cumplan los requisitos legales.</p><div className={styles.warning}><FileCheck2 aria-hidden="true" /><p>Son límites de prima que pueden quedar exentos, no cantidades de ahorro garantizado.<br /><strong>El exceso sobre esos límites constituye retribución en especie.</strong></p></div></div><aside className={styles.companyPanel}><p className={styles.sideEyebrow}>PARA LA EMPRESA</p><h3>Tratamiento para la empresa</h3><p>La prima puede tener la consideración de gasto de personal fiscalmente deducible cuando está correctamente instrumentada y contabilizada.</p><ul>{companyPoints.map(point=><li key={point}><Check aria-hidden="true" />{point}</li>)}</ul></aside></div><div className={styles.legal}><p>Información general aplicable al régimen común. Los territorios forales pueden establecer límites o tratamientos diferentes. La aplicación concreta debe revisarse con la asesoría fiscal y laboral de la empresa.</p><p>Esta información no sustituye el asesoramiento fiscal, laboral ni la documentación contractual de la modalidad elegida.</p></div></div></section>;
}

// Referencias internas de mantenimiento: artículo 42.3.c de la Ley 35/2006 del IRPF; artículo 46 del Reglamento del IRPF; artículo 15.e de la Ley 27/2014 del Impuesto sobre Sociedades.
