import Image from 'next/image';
import { BriefcaseBusiness, FileCheck2, Scale, Wrench } from 'lucide-react';
import styles from './business-cyber-protection-section.module.css';

const areas = [
  ['01', 'RESPUESTA ANTE INCIDENTES', 'Primeras actuaciones y coordinación especializada', 'Puede incluir orientación inicial, coordinación técnica y seguimiento para analizar el incidente, limitar sus efectos y organizar la recuperación.', ['valoración inicial del alcance', 'coordinación de los profesionales implicados'], Wrench],
  ['02', 'SISTEMAS Y CONTINUIDAD', 'Recuperación de datos, sistemas y actividad', 'Puede contemplar trabajos de análisis, restauración y recuperación cuando el incidente afecta a equipos, aplicaciones o información.', ['análisis y remediación técnica', 'gastos o pérdidas por interrupción según condiciones'], FileCheck2],
  ['03', 'PRIVACIDAD Y RESPONSABILIDAD', 'Apoyo ante datos afectados y reclamaciones', 'Cuando existe una posible vulneración de información, puede ser necesario valorar obligaciones legales, comunicaciones y responsabilidad frente a terceros.', ['evaluación de la afectación', 'defensa o asistencia jurídica cuando corresponda'], Scale],
  ['04', 'FRAUDE Y CIBERDELINCUENCIA', 'Protección ante determinados engaños digitales', 'Algunas modalidades pueden estudiar pérdidas derivadas de suplantación, manipulación de pagos u otros actos de ciberdelincuencia.', ['fraude por transferencia', 'determinadas pérdidas económicas según cobertura'], BriefcaseBusiness],
] as const;

export function BusinessCyberProtectionSection(){return <section className={styles.section} aria-labelledby="cyber-protection-title"><header className={styles.header}><p className="kicker">QUÉ PUEDE APORTAR UNA SOLUCIÓN DE CIBERPROTECCIÓN</p><h2 id="cyber-protection-title">La respuesta necesita coordinación técnica, legal y económica</h2><p>La combinación exacta depende de la modalidad contratada. Estas son las áreas que pueden estudiarse para responder a las consecuencias de un incidente.</p></header><div className={styles.story}><div className={styles.infrastructurePhoto}><Image src="/images/ciberseguridad/infraestructura-servidores.jpg" alt="Racks de servidores que sostienen la continuidad de los sistemas" fill sizes="(max-width: 700px) 100vw, 46vw" /></div><div className={styles.storyCopy}><p>SISTEMAS Y CONTINUIDAD</p><h3>Recuperar la actividad puede exigir algo más que volver a encender los equipos</h3><span>Un incidente puede afectar sistemas, aplicaciones o información. La respuesta puede requerir análisis y recuperación técnica según el incidente y la solución contratada.</span></div></div><div className={styles.areas}>{areas.map(([number,label,title,text,points,Icon])=><article className={styles.area} key={number}><div className={styles.areaNumber}>{number}</div><Icon aria-hidden="true" className={styles.areaIcon}/><div className={styles.areaBody}><p>{label}</p><h3>{title}</h3><span>{text}</span><ul>{points.map(point=><li key={point}>{point}</li>)}</ul></div></article>)}</div><p className={styles.note}>Las coberturas, servicios, límites, franquicias y exclusiones dependen de la modalidad contratada y del análisis del incidente.</p></section>}
