import Link from 'next/link';
import { ArrowRight, BedDouble, Check, Clock3, Globe2, HeartPulse, MessageCircleMore, ReceiptText, Stethoscope, WalletCards } from 'lucide-react';
import styles from './health-insurance-insights.module.css';

const highlights = [
  { title: 'Cobertura ambulatoria o completa', text: 'La ambulatoria incluye consultas, especialistas, pruebas y tratamientos. La completa añade hospitalización, cirugía y otras coberturas asociadas.', icon: BedDouble },
  { title: 'Cuadro médico o reembolso', text: 'El cuadro médico te da acceso a profesionales y centros concertados. El reembolso te permite elegir y recuperar una parte según tu póliza.', icon: WalletCards },
  { title: 'Copagos: sin copagos, bajo o alto', text: 'Hay opciones sin copagos y otras con distintos niveles de copago. Influyen en la prima y en lo que pagas cada vez que utilizas la póliza.', icon: ReceiptText },
];
const decisions = [
  ['01','Hospitalización','¿Incluye ingreso y cirugía?','Las modalidades ambulatorias no incluyen hospitalización. Las completas sí.',BedDouble],
  ['02','Copagos','¿Pagas cada vez que usas la póliza?','Puedes elegir sin copagos, con copago bajo o alto. Afecta a la prima y a tu coste por uso.',ReceiptText],
  ['03','Elección médica','¿Cuadro concertado o reembolso?','El cuadro médico te da acceso a la red concertada. El reembolso te permite elegir y recuperar parte de la factura.',HeartPulse],
  ['04','Carencias y aceptación','¿Cuándo puedes usar cada cobertura?','Algunas coberturas tienen periodos de carencia y están sujetas a cuestionario de salud.',Clock3],
  ['05','Dónde y para qué necesitas cobertura','¿La necesitas para residir, estudiar o tener cobertura fuera de España?','No todos los productos tienen el mismo territorio ni sirven para el mismo objetivo.',Globe2],
] as const;

export function HealthCoverageHighlightsSection() { return <section className={styles.coverage} aria-labelledby="health-coverage-title"><div className={`container-shell ${styles.coverageShell}`}><div className={styles.coverageIntro}><p className={styles.eyebrow}>COBERTURAS DESTACADAS</p><h2 id="health-coverage-title">Qué cambia de verdad entre un seguro y otro</h2><p>Antes de comparar precios, conviene saber qué incluye cada modalidad, qué queda fuera y cuánto pagarás cuando utilices la póliza.</p></div><div className={styles.highlightList}>{highlights.map(({title,text,icon:Icon})=><article key={title} className={styles.highlight}><span aria-hidden="true"><Icon /></span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div><svg className={styles.coverageFamily} aria-hidden="true" viewBox="0 0 250 230"><path d="M51 20c-14 0-23 12-23 26 0 9 5 17 12 21l-5 28-22 30 13 8 15-20 3 57h17l3-57 16 20 13-8-23-30-5-28c8-4 12-12 12-21 0-14-9-26-23-26Zm118 0c-14 0-23 12-23 26 0 9 5 17 12 21l-5 28-22 30 13 8 15-20 3 57h17l3-57 16 20 13-8-23-30-5-28c8-4 12-12 12-21 0-14-9-26-23-26ZM105 66c-10 0-17 8-17 18 0 7 4 13 9 16l-3 19-15 20 10 6 10-13 2 37h13l2-37 10 13 10-6-15-20-3-19c5-3 9-9 9-16 0-10-7-18-17-18Zm31 17c-8 0-13 7-13 15 0 6 3 11 7 13l-3 15-12 16 9 6 8-11 2 30h11l2-30 8 11 9-6-12-16-3-15c4-2 7-7 7-13 0-8-5-15-13-15Z" /></svg><svg className={styles.coverageLine} aria-hidden="true" viewBox="0 0 1440 90" preserveAspectRatio="none"><path d="M-30 53c266-52 429 54 687 5 246-47 394 37 826-22" /></svg></div></section>; }

export function HealthDecisionGuideSection() { return <section className={styles.decisions} aria-labelledby="health-decisions-title"><div className={`container-shell ${styles.decisionShell}`}><div className={styles.decisionIntro}><p className={styles.eyebrow}>ANTES DE CONTRATAR</p><h2 id="health-decisions-title">Cinco aspectos que conviene revisar antes de contratar</h2><p>El precio es importante, pero no explica por sí solo cómo funcionará la póliza. Hospitalización, copagos, elección médica, carencias y ámbito de cobertura pueden cambiar mucho la experiencia.</p><Link href="/contacto" className={styles.orangeAction}>Revisar mi situación <ArrowRight aria-hidden="true" /></Link></div><div className={styles.decisionTrack}>{decisions.map(([num,title,question,text,Icon])=><article key={num} className={styles.decision}><div className={styles.decisionHead}><span className={styles.number}>{num}</span><span className={styles.decisionIcon} aria-hidden="true"><Icon /></span></div><h3>{title}</h3><strong>{question}</strong><p>{text}</p></article>)}<svg aria-hidden="true" viewBox="0 0 1000 42" preserveAspectRatio="none"><path d="M15 22h945" />{[15,252,490,728,960].map(x=><circle key={x} cx={x} cy="22" r="4" />)}<path d="m978 16 10 6-10 6" /></svg></div><aside className={styles.guideClosing}><span aria-hidden="true"><MessageCircleMore /></span><div><h3>¿No sabes cuál elegir?</h3><p>Cuéntanos qué buscas y te ayudaremos a distinguir qué opciones tienen sentido para tu caso y cuáles puedes descartar.</p></div><Link href="/contacto">Revisar mi caso <ArrowRight aria-hidden="true" /></Link></aside></div></section>; }
