import { BedDouble, Check, Clock3, Globe2, HeartPulse, ReceiptText, Stethoscope, WalletCards } from 'lucide-react';
import styles from './health-insurance-insights.module.css';
import { useLocale } from 'next-intl';

const highlights = [
  { title: 'Cobertura ambulatoria o completa', text: 'La ambulatoria incluye consultas, especialistas, pruebas y tratamientos. La completa añade hospitalización, cirugía y otras coberturas asociadas.', icon: BedDouble },
  { title: 'Cuadro médico o reembolso', text: 'El cuadro médico te da acceso a profesionales y centros concertados. El reembolso te permite elegir y recuperar una parte según tu póliza.', icon: WalletCards },
  { title: 'Copagos: sin copagos, bajo o alto', text: 'Hay opciones sin copagos y otras con distintos niveles de copago. Influyen en la prima y en lo que pagas cada vez que utilizas la póliza.', icon: ReceiptText },
];
const decisions = [
  ['01','Copagos y uso previsto','¿Cómo esperas utilizar la póliza?','Relaciona la estructura de pago con la frecuencia y el tipo de servicios que esperas utilizar.',ReceiptText],
  ['02','Hospitalización','¿Incluye ingreso y cirugía?','Confirma si el ingreso y la cirugía forman parte de la modalidad que estás revisando.',BedDouble],
  ['03','Cuadro médico o reembolso','¿Red concertada o profesionales fuera de ella?','Comprueba si te basta la red concertada o si necesitas valorar una modalidad de reembolso.',HeartPulse],
  ['04','Carencias','¿Cuándo puedes usar cada cobertura?','Las carencias indican cuándo puedes utilizar ciertas coberturas; no son lo mismo que la disponibilidad de citas.',Clock3],
  ['05','Cuestionario y preexistencias','¿Qué se valora al suscribir la póliza?','La declaración de salud puede influir en la aceptación y las exclusiones. Las autorizaciones previas son otro requisito de uso.',Globe2],
] as const;

export function HealthCoverageHighlightsSection() {
  const en = useLocale() === 'en';
  const items = en ? [
    { title: 'Outpatient or comprehensive cover', text: 'Outpatient cover includes consultations, specialists, tests and treatments. Comprehensive cover adds hospitalisation, surgery and related benefits.', icon: BedDouble },
    { title: 'Provider network or reimbursement', text: 'A provider network gives you access to contracted professionals and centres. Reimbursement lets you choose and recover part of the cost according to your policy.', icon: WalletCards },
    { title: 'Co-payments: none, low or high', text: 'Some plans have no co-payments while others have different co-payment levels. This affects the premium and what you pay each time you use the policy.', icon: ReceiptText },
  ] : highlights;
  return <section className={styles.coverage} aria-labelledby="health-coverage-title"><div className={`container-shell ${styles.coverageShell}`}><div className={styles.coverageIntro}><p className={styles.eyebrow}>{en ? 'KEY COVER POINTS' : 'COBERTURAS DESTACADAS'}</p><h2 id="health-coverage-title">{en ? 'What really changes from one policy to another' : 'Qué cambia de verdad entre un seguro y otro'}</h2><p>{en ? 'Before comparing prices, it helps to know what each plan includes, what may differ and what you pay when you use it.' : 'Antes de comparar precios, conviene saber qué incluye cada modalidad, qué queda fuera y cuánto pagarás cuando utilices la póliza.'}</p></div><div className={styles.highlightList}>{items.map(({title,text,icon:Icon})=><article key={title} className={styles.highlight}><span aria-hidden="true"><Icon /></span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div><svg className={styles.coverageFamily} aria-hidden="true" viewBox="0 0 250 230"><path d="M51 20c-14 0-23 12-23 26 0 9 5 17 12 21l-5 28-22 30 13 8 15-20 3 57h17l3-57 16 20 13-8-23-30-5-28c8-4 12-12 12-21 0-14-9-26-23-26Zm118 0c-14 0-23 12-23 26 0 9 5 17 12 21l-5 28-22 30 13 8 15-20 3 57h17l3-57 16 20 13-8-23-30-5-28c8-4 12-12 12-21 0-14-9-26-23-26ZM105 66c-10 0-17 8-17 18 0 7 4 13 9 16l-3 19-15 20 10 6 10-13 2 37h13l2-37 10 13 10-6-15-20-3-19c5-3 9-9 9-16 0-10-7-18-17-18Zm31 17c-8 0-13 7-13 15 0 6 3 11 7 13l-3 15-12 16 9 6 8-11 2 30h11l2-30 8 11 9-6-12-16-3-15c4-2 7-7 7-13 0-8-5-15-13-15Z" /></svg><svg className={styles.coverageLine} aria-hidden="true" viewBox="0 0 1440 90" preserveAspectRatio="none"><path d="M-30 53c266-52 429 54 687 5 246-47 394 37 826-22" /></svg></div></section>;
}

export function HealthDecisionGuideSection() { const en = useLocale() === 'en'; const visible = en ? [['01','Co-payments and expected use','How do you expect to use the policy?','Relate the payment structure to how often and for which services you expect to use the cover.',ReceiptText],['02','Hospitalisation','Does it include inpatient and surgical care?','Confirm whether inpatient and surgical care form part of the plan you are reviewing.',BedDouble],['03','Medical network or reimbursement','Contracted network or providers outside it?','Check whether the contracted network is enough or whether you need to consider reimbursement.',HeartPulse],['04','Waiting periods','When can you use each benefit?','Waiting periods indicate when certain benefits can be used; they are different from appointment availability.',Clock3],['05','Health questionnaire and pre-existing conditions','What is assessed when the policy is underwritten?','The health declaration may affect acceptance and exclusions. Prior authorisation is a separate use requirement.',Globe2]] as const : decisions; return <section className={styles.decisions} aria-labelledby="health-five-checks-title"><div className={`container-shell ${styles.decisionShell}`}><div className={styles.decisionIntro}><p className={styles.eyebrow}>{en ? 'BEFORE YOU CHOOSE' : 'ANTES DE ELEGIR'}</p><h2 id="health-five-checks-title">{en ? 'Five things to check before choosing health insurance' : 'Cinco cosas que conviene comprobar antes de elegir un seguro de salud'}</h2><p>{en ? 'Before choosing, review these five questions against the specific policy and how you expect to use it.' : 'Antes de elegir, revisa estas cinco preguntas en la póliza concreta y según el uso que esperas hacer.'}</p></div><div className={styles.decisionTrack}>{visible.map(([num,title,question,text,Icon])=><article key={num} className={styles.decision}><div className={styles.decisionHead}><span className={styles.number}>{num}</span><span className={styles.decisionIcon} aria-hidden="true"><Icon /></span></div><h3>{title}</h3><strong>{question}</strong><p>{text}</p></article>)}<svg aria-hidden="true" viewBox="0 0 1000 42" preserveAspectRatio="none"><path d="M15 22h945" />{[15,252,490,728,960].map(x=><circle key={x} cx={x} cy="22" r="4" />)}<path d="m978 16 10 6-10 6" /></svg></div></div></section>; }
