export type HomeLocale = 'es' | 'en';

export type HomeFaq = { q: string; a: string };

export type HomeContent = {
  meta: { title: string; description: string; ogTitle: string; ogDescription: string };
  hero: { products: Record<string, string>; businessLabel: string; businessTitle: string; businessDescription: string; cyberLabel: string; cyberTitle: string; cyberDescription: string };
  trust: { kicker: string; title: string; badges: { title: string; copy: string }[]; response: string; imageAlt: string; imageTitle: string; imageCopy: string };
  products: { eyebrow: string; title: string; intro: string; descriptions: Record<string, string>; benefits: Record<string, string[]>; cta: string };
  profiles: { title: string; intro: string; items: { title: string; copy: string; cta: string }[] };
  stats: { aria: string; labels: string[]; imageAlt: string };
  comparison: { kicker: string; title: string; intro: string; steps: string[]; cta: string[]; profiles: { title: string; description: string; bullets: string[] }[]; imageAlt: string; imageKicker: string; imageTitle: string; imageBullets: string[]; whatsapp: string };
  agent: { kicker: string; title: string; copy: string; bullets: string[]; cta: string; aria: string; adeslasTitle: string; adeslasDescription: string; adeslasCta: string; imageAlt: string };
  how: { title: string; intro: string; cta: string; whatsapp: string };
  blog: { kicker: string; title: string; intro: string; cta: string };
  faq: { kicker: string; title: string; intro: string; whatsapp: string; whatsappAria: string; contact: string; contactAria: string; items: HomeFaq[]; expand: string; ask: string; productLinks: string[] };
  credentials: { aria: string; kicker: string; items: { label: string; sub: string }[] };
  guarantee: { title: string; compact: string; body: string; cta: string; whatsapp: string };
  finalCta: { title: string; body: string; response: string; contact: string; whatsapp: string; imageAlt: string };
  mascot: { imageAlt: string; badge: string; kicker: string; title: string; body: string; bullets: string[]; cta: string; whatsapp: string };
  reviews: { title: string; subtitle: string; all: string; verified: string; previous: string; next: string; review: string };
  zones: { label: string; title: string; linkPrefix: string };
};

const es: HomeContent = {
  meta: { title: 'Asesor de Seguros en Madrid — Salud, Vida y Más | VPI', description: 'Agente de seguros registrado DGSFP en Madrid. Salud, vida, dental y mascotas con criterio profesional y registro en la DGSFP. Sin presión comercial.', ogTitle: 'Asesor de Seguros en Madrid — Salud, Vida y Más | VPI', ogDescription: 'Agente de seguros registrado DGSFP en Madrid. Seguros de salud, vida, dental y mascotas con criterio profesional y registro en la DGSFP.' },
  hero: { products: { salud: 'SALUD', mascotas: 'MASCOTAS', dental: 'DENTAL', accidentes: 'ACCIDENTES', viaje: 'VIAJE', decesos: 'DECESOS' }, businessLabel: 'SALUD PARA EMPRESAS', businessTitle: 'Salud para tu equipo', businessDescription: 'Coberturas desde dos asegurados y distintas modalidades.', cyberLabel: 'CIBERSEGURIDAD PARA EMPRESAS', cyberTitle: 'Continuidad del negocio', cyberDescription: 'Respuesta ante incidentes e interrupciones de actividad.' },
  trust: { kicker: 'Más de 10 años protegiendo lo importante', title: 'Confianza, experiencia y cuidado personalizado', badges: [{ title: 'Confianza', copy: 'Miles de conversaciones y familias orientadas con cercanía, claridad y seguimiento.' }, { title: 'Experiencia', copy: 'Más de 10 años asesorando y orientando con criterio, no con prisas.' }, { title: 'Cuidado personalizado', copy: 'Cada caso se revisa con contexto: tu etapa, tus prioridades y la protección que buscas.' }, { title: 'Consulta sin compromiso', copy: 'Puedes empezar por WhatsApp, llamada o formulario corto y seguir por el canal que te resulte más cómodo, siempre sin compromiso.' }], response: 'Respondemos en nuestro horario de atención. Siempre. Sin excusas. Sin call centers.', imageAlt: 'Apretón de manos profesional que simboliza el compromiso, la transparencia y el acompañamiento experto de Valentín Protección Integral', imageTitle: 'Protegemos tu tranquilidad', imageCopy: 'Más de 10 años ayudando a familias y particulares a sentirse seguros con sus decisiones.' },
  products: { eyebrow: 'NUESTRAS SOLUCIONES', title: 'Protección para cada etapa de tu vida', intro: 'Descubre las opciones que podemos ayudarte a valorar según tu situación, tu familia y lo que quieres proteger.', descriptions: { salud: 'Salud privada según tu situación.', mascotas: 'Veterinaria, RC y opciones para cuidar de los tuyos.', dental: 'Revisiones y tratamientos según tu modalidad.', accidentes: 'Protección ante imprevistos personales.', viaje: 'Opciones para cada destino y viaje.', decesos: 'Previsión para cada familia.' }, benefits: { salud: ['Criterio, no solo precio.', 'Copago y reembolso claros.'], mascotas: ['Prioriza veterinaria, RC o ambas.', 'Revisa límites y servicios.'], dental: ['Actos, descuentos y tarifas.', 'Todo explicado con claridad.'], accidentes: ['Para quien no puede permitirse parar.', 'Contratación ágil.'], viaje: ['Aclara límites y destinos.', 'Elige según cada viaje.'], decesos: ['Menos gestiones en momentos delicados.', 'Previsión con serenidad.'] }, cta: 'Ver cobertura' },
  profiles: { title: 'Encuentra lo que necesitas según tu situación', intro: 'Cada etapa de la vida tiene sus prioridades. Elige el perfil que mejor te describe y descubre la protección que realmente necesitas.', items: [{ title: 'Joven Profesional', copy: 'Acabas de emanciparte o tienes hipoteca reciente. Protege lo que estás construyendo.', cta: 'Ver mi protección →' }, { title: 'Familias', copy: 'Protege a quienes más quieres. Salud, dental, vida y decesos para toda la familia.', cta: 'Proteger a los míos →' }, { title: 'Seniors', copy: 'Más de 60 años y quieres tener todo en orden. Tranquilidad para ti y los tuyos.', cta: 'Tener todo en orden →' }, { title: 'Autónomos', copy: 'Dedúcete hasta 500€ en el IRPF. Aprovecha las ventajas fiscales que te corresponden.', cta: 'Ver ventajas fiscales →' }] },
  stats: { aria: 'Estadísticas de impacto', labels: ['Años de experiencia', 'Familias protegidas', 'Asesoría cercana'], imageAlt: 'Rosa y Sebastián, equipo Valentín Protección Integral' },
  comparison: { kicker: 'Cómo decidir mejor', title: 'Entiende tus coberturas con acompañamiento real', intro: 'No se trata solo de ver coberturas. Se trata de entender qué encaja contigo, qué cambia entre modalidades y cómo empezar por el canal que te resulte más cómodo.', steps: ['Quiero una primera orientación', 'Afina tu modalidad', 'Empezar ahora'], cta: ['Quiero una primera orientación', 'Afina tu modalidad', 'Empezar ahora'], profiles: [{ title: 'Quiero una primera orientación', description: 'Ideal si todavía estás ordenando opciones y quieres entender qué te conviene revisar primero.', bullets: ['Te explicamos con claridad', 'Resolvemos dudas sin prisa comercial', 'Te ayudamos a decidir mejor'] }, { title: 'Ya sé el ramo, me falta afinar modalidad', description: 'Para quien ya sabe si busca SALUD, VIDA, MASCOTAS, VIAJE, DENTAL o DECESOS y necesita aterrizar qué opción encaja mejor.', bullets: ['Con y sin copago', 'Hipoteca o protección familiar', 'Veterinaria, RC o extras'] }, { title: 'Necesito resolverlo rápido', description: 'Cuando prefieres ir al grano sin perder una orientación humana y profesional.', bullets: ['WhatsApp contextual', 'Formulario corto', 'Posibilidad de llamada'] }], imageAlt: 'Reunión de asesoramiento para revisar opciones de seguro con claridad', imageKicker: 'Una decisión mejor empieza con una conversación clara', imageTitle: 'Te escuchamos, te explicamos las coberturas y te acompañamos de verdad', imageBullets: ['Escuchamos tu situación y tus prioridades', 'Traducimos coberturas y matices a lenguaje claro', 'Te guiamos hacia SALUD, VIDA, ELECTRODOMÉSTICOS o NEGOCIOS'], whatsapp: 'Hola, quiero una primera orientación para saber por dónde empezar.' },
  agent: { kicker: 'Atención humana y experta', title: 'Rosa y Sebastián: más de 10 años acompañándote para decidir con seguridad', copy: 'Valentín Protección Integral es un proyecto cofundado por Rosa y Sebastián. Ambos acompañan cada caso con una mirada transparente y profesional, para que entiendas tus opciones antes de contratar.', bullets: ['Asesoría según tu etapa y prioridades', 'Asesoramiento detallado sobre coberturas y modalidades'], cta: 'Consulta sin compromiso', aria: 'Contactar para consulta sin compromiso', adeslasTitle: 'Rosa también figura en el buscador oficial de agentes de SegurCaixa Adeslas', adeslasDescription: 'Si prefieres dejar tus datos directamente en la página oficial para Boadilla del Monte, puedes acceder desde aquí.', adeslasCta: 'Ver canal oficial', imageAlt: 'Rosa y Sebastián asesorando de forma personalizada, con claridad y confianza en cada póliza' },
  how: { title: 'Cómo te ayudamos a decidir mejor', intro: 'Un proceso claro, humano y sin presiones.', cta: 'Ver cómo te ayudamos', whatsapp: 'Hola, quiero orientación sobre cómo elegir un seguro.' },
  blog: { kicker: 'Tu seguridad es lo primero', title: 'Por qué las familias confían en Valentín', intro: 'Te ayudamos a resolver dudas reales y a mantenerte al día sobre seguros con nuestros artículos especializados.', cta: 'Ir al blog' },
  faq: { kicker: 'Resolvemos tus dudas', title: '¿Tienes preguntas antes de empezar?', intro: 'Aquí respondemos con más detalle a preguntas habituales. Y si prefieres una explicación más personal, puedes escribirnos por WhatsApp o pedir orientación.', whatsapp: 'Hola, tengo una duda sobre seguros y quiero una orientación.', whatsappAria: 'Hablar con Rosa Valentín por WhatsApp', contact: 'Consulta sin compromiso', contactAria: 'Solicitar consulta sin compromiso por formulario', items: [{ q: '¿Puedo recibir asesoramiento sin compromiso?', a: 'Sí. La orientación es 100% gratuita y sin compromiso. Puedes consultar, entender mejor tus opciones y decidir con calma si quieres avanzar o no.' }, { q: '¿Trabajáis con distintas opciones de seguro?', a: 'Trabajamos con una de las compañías más sólidas del mercado para ofrecerte la cobertura que mejor se adapta a ti.' }, { q: '¿Me ayudáis a revisar coberturas?', a: 'Ese es nuestro principal valor. No somos un portal automático de precios; traducimos la letra pequeña, te explicamos diferencias reales (ej. copago vs reembolso) y te ayudamos a elegir con criterio.' }, { q: '¿Qué necesito para contratar?', a: 'Una vez hayamos elegido la mejor opción, nosotros nos encargamos de toda la gestión administrativa. Solo necesitaremos tus datos básicos y confirmar las condiciones pactadas.' }, { q: '¿Puedo resolver dudas después de contratar?', a: 'Por supuesto. Nuestro trabajo no termina al firmar la póliza. Seguiremos a tu lado para ayudarte con autorizaciones, partes de siniestro o cambios en tus condiciones.' }, { q: '¿Qué tipo de seguros puedo consultar?', a: 'Somos especialistas en seguros de SALUD, VIDA, MASCOTAS, VIAJES, DENTAL, ACCIDENTES y DECESOS. Además, ofrecemos soluciones específicas para familias, seniors, extranjeros y autónomos.' }], expand: 'Haz clic para ver una explicación más clara y práctica.', ask: 'Pedir orientación', productLinks: ['Ver SALUD', 'Ver MASCOTAS', 'Ver VIAJE'] },
  credentials: { aria: 'Credenciales profesionales', kicker: 'Asesoría con respaldo profesional real', items: [{ label: 'Agente de seguros registrada', sub: 'Registro DGSyFP oficial' }, { label: 'Formación continua', sub: 'Certificada cada año' }, { label: '+10 años de experiencia', sub: 'Especialista en Madrid' }, { label: 'Orientación de seguros', sub: 'Registro oficial de la actividad' }] },
  guarantee: { title: 'Revisamos tu presupuesto', compact: 'Tráenos cualquier presupuesto y lo revisamos contigo entre las modalidades que podemos distribuir, con honestidad.', body: 'Tráenos cualquier presupuesto que tengas y comparamos las modalidades que podemos distribuir, para que valores la opción que mejor se ajusta a tu caso.', cta: 'Ver cómo funciona →', whatsapp: 'Hola, quiero solicitar una comparación gratuita de mi presupuesto.' },
  finalCta: { title: '¿Hablamos sobre lo que te preocupa?', body: 'Una llamada breve suele ser el camino más rápido para despejar dudas. Desde ahí vemos juntos qué producto tiene sentido para ti de forma directa y profesional.', response: 'Tiempo medio de respuesta hoy: menos de 18 minutos', contact: 'Elegir mi seguro con Rosa', whatsapp: 'Hola, quiero una consulta sin compromiso para revisar qué seguro me encaja mejor.', imageAlt: 'Sebastián, asesor del equipo de Valentín especializado en vida y salud, aportando cercanía y rigor técnico' },
  mascot: { imageAlt: 'Asesor de seguros acompañando a una familia en Madrid durante una consulta personalizada', badge: '+10 años orientando', kicker: 'Tu punto de apoyo', title: 'Orientación humana para decisiones importantes', body: 'Hemos diseñado esta experiencia para que te sientas acompañado en cada paso. Sin tecnicismos, sin presiones y con una mirada experta sobre lo que de verdad importa.', bullets: ['Ordenamos prioridades antes de decidir.', 'Aterrizamos coberturas a lenguaje claro.', 'Te señalamos qué conviene revisar de verdad.', 'Acompañamiento por WhatsApp o llamada.'], cta: 'Explorar cómo ayudamos', whatsapp: 'Hola, quiero una orientación para entender mejor qué seguro me conviene.' },
  reviews: { title: '', subtitle: '', all: 'Ver todas en Google →', verified: 'opiniones verificadas en Google', previous: 'Reseña anterior', next: 'Siguiente reseña', review: 'Ver reseña' },
  zones: { label: 'Cobertura local', title: 'Atendemos en todo el noroeste de Madrid', linkPrefix: 'Seguros en ' },
};

const en: HomeContent = {
  ...es,
  meta: { title: 'Insurance advice in Madrid — Health, Life and More | VPI', description: 'DGSFP-registered insurance advice in Madrid. Health, life, dental and pet insurance explained clearly, without sales pressure.', ogTitle: 'Insurance advice in Madrid — Health, Life and More | VPI', ogDescription: 'Professional insurance guidance in Madrid for health, life, dental and pet cover.' },
  hero: { products: { salud: 'HEALTH', mascotas: 'PETS', dental: 'DENTAL', accidentes: 'ACCIDENTS', viaje: 'TRAVEL', decesos: 'FUNERAL' }, businessLabel: 'BUSINESS HEALTH', businessTitle: 'Health cover for your team', businessDescription: 'Cover for two or more people, with different options to choose from.', cyberLabel: 'BUSINESS CYBERSECURITY', cyberTitle: 'Business continuity', cyberDescription: 'Support when incidents interrupt your activity.' },
  trust: { ...es.trust, kicker: 'Over 10 years protecting what matters', title: 'Trust, experience and personal care', badges: [{ title: 'Trust', copy: 'Thousands of conversations and families supported with care, clarity and follow-up.' }, { title: 'Experience', copy: 'Over 10 years advising with judgement, never rushing the decision.' }, { title: 'Personal care', copy: 'We review every case in context: your stage, priorities and the protection you need.' }, { title: 'No-obligation guidance', copy: 'Start by WhatsApp, phone or a short form, using whichever channel suits you best.' }], response: 'We reply during our opening hours. Always. No excuses. No call centres.', imageAlt: 'Professional handshake symbolising Valentín Protección Integral’s commitment, transparency and expert support', imageTitle: 'Protecting your peace of mind', imageCopy: 'For over 10 years, we have helped families and individuals feel confident about their insurance decisions.' },
  products: { ...es.products, eyebrow: 'OUR SOLUTIONS', title: 'Protection for every stage of life', intro: 'Explore the options we can help you assess around your situation, your family and what you want to protect.', descriptions: { salud: 'Private health cover for your situation.', mascotas: 'Veterinary care, liability and options for those you care for.', dental: 'Check-ups and treatment according to your plan.', accidentes: 'Protection when the unexpected happens.', viaje: 'Options for every destination and journey.', decesos: 'Planning for every family.' }, benefits: { salud: ['Good judgement, not price alone.', 'Clear copay and reimbursement options.'], mascotas: ['Prioritise veterinary care, liability or both.', 'Review limits and services.'], dental: ['Treatments, discounts and fees.', 'Everything explained clearly.'], accidentes: ['For people who cannot afford to stop.', 'Straightforward arrangement.'], viaje: ['Clarify limits and destinations.', 'Choose for each journey.'], decesos: ['Fewer arrangements at difficult times.', 'Planning with peace of mind.'] }, cta: 'View cover' },
  profiles: { title: 'Find what you need for your situation', intro: 'Every stage of life has different priorities. Choose the profile that best describes you and discover the protection you really need.', items: [{ title: 'Young professionals', copy: 'You have recently moved out or taken on a mortgage. Protect what you are building.', cta: 'See my protection →' }, { title: 'Families', copy: 'Protect the people who matter most. Health, dental, life and funeral cover for the whole family.', cta: 'Protect my family →' }, { title: 'Seniors', copy: 'You are over 60 and want everything in order. Peace of mind for you and yours.', cta: 'Put everything in order →' }, { title: 'Self-employed', copy: 'Claim up to €500 in income tax relief. Make the most of the tax benefits available to you.', cta: 'See tax benefits →' }] },
  stats: { aria: 'Impact statistics', labels: ['Years of experience', 'Families protected', 'Personal guidance'], imageAlt: 'Rosa and Sebastián, Valentín Protección Integral team' },
  comparison: { ...es.comparison, kicker: 'How to decide well', title: 'Understand your cover with real support', intro: 'It is not just about looking at cover. It is about understanding what suits you, what changes between options and which way of getting started feels most comfortable.', cta: ['Get initial guidance', 'Refine your option', 'Get started'], profiles: [{ title: 'I would like initial guidance', description: 'Ideal if you are still weighing up options and want to know what to review first.', bullets: ['We explain things clearly', 'Questions are welcome', 'We help you decide well'] }, { title: 'I know the type of cover, but need the right option', description: 'For anyone who knows whether they need HEALTH, LIFE, PET, TRAVEL, DENTAL or FUNERAL cover and wants to identify the right option.', bullets: ['With or without copay', 'Mortgage or family protection', 'Veterinary care, liability or extras'] }, { title: 'I need to sort it quickly', description: 'When you want to get to the point without losing human, professional guidance.', bullets: ['Contextual WhatsApp support', 'Short form', 'Option to arrange a call'] }], imageAlt: 'Insurance guidance meeting to review options clearly', imageKicker: 'A better decision starts with a clear conversation', imageTitle: 'We listen, explain the cover and genuinely support you', imageBullets: ['We listen to your situation and priorities', 'We translate cover and details into clear language', 'We guide you towards HEALTH, LIFE, HOME or BUSINESS cover'], whatsapp: 'Hello, I would like some initial guidance on where to start.' },
  agent: { ...es.agent, kicker: 'Human, expert support', title: 'Rosa and Sebastián: over 10 years helping you decide with confidence', copy: 'Valentín Protección Integral is a project co-founded by Rosa and Sebastián. They approach each case with transparency and professional care, so you understand your options before arranging cover.', bullets: ['Advice based on your stage and priorities', 'Detailed guidance on cover and policy options'], cta: 'Book a no-obligation consultation', aria: 'Contact us for a no-obligation consultation', adeslasTitle: 'Rosa is also listed in the official SegurCaixa Adeslas agent directory', adeslasDescription: 'If you prefer to leave your details directly on the official page for Boadilla del Monte, you can access it here.', adeslasCta: 'View official channel', imageAlt: 'Rosa and Sebastián providing personal insurance advice, with clarity and confidence at the centre' },
  how: { title: 'How we help you decide', intro: 'A clear, human process without pressure.', cta: 'See how we help', whatsapp: 'Hello, I would like guidance on choosing insurance.' },
  blog: { kicker: 'Your security comes first', title: 'Why families trust Valentín', intro: 'We help you resolve real questions and keep up to date with insurance through our specialist articles.', cta: 'Go to the blog' },
  faq: { ...es.faq, kicker: 'We answer your questions', title: 'Questions before you get started?', intro: 'Here we answer common questions in more detail. If you would prefer a personal explanation, you can message us on WhatsApp or ask for guidance.', whatsapp: 'Hello, I have a question about insurance and would like some guidance.', whatsappAria: 'Speak to Rosa Valentín on WhatsApp', contact: 'No-obligation consultation', contactAria: 'Request a no-obligation consultation by form', items: [{ q: 'Can I get advice without any obligation?', a: 'Yes. Our guidance is completely free and without obligation. You can ask questions, understand your options and take your time deciding whether to proceed.' }, { q: 'Do you work with different insurance options?', a: 'We work with one of the strongest companies in the market to offer cover that fits you best.' }, { q: 'Can you help me review my cover?', a: 'That is our main value. We are not an automated price portal; we translate the small print, explain real differences such as copay versus reimbursement, and help you choose with confidence.' }, { q: 'What do I need to arrange a policy?', a: 'Once we have chosen the best option, we handle the administration. We only need your basic details and confirmation of the agreed terms.' }, { q: 'Can I ask questions after taking out a policy?', a: 'Of course. Our work does not end when the policy is signed. We remain available to help with authorisations, claims or changes to your policy.' }, { q: 'What types of insurance can I ask about?', a: 'We specialise in HEALTH, LIFE, PET, TRAVEL, DENTAL, ACCIDENT and FUNERAL insurance. We also offer specific solutions for families, seniors, international residents and self-employed people.' }], expand: 'Click to see a clearer, practical explanation.', ask: 'Ask for guidance', productLinks: ['View HEALTH', 'View PET', 'View TRAVEL'] },
  credentials: { aria: 'Professional credentials', kicker: 'Advice backed by real professional credentials', items: [{ label: 'Registered insurance agent', sub: 'Official DGSyFP register' }, { label: 'Continuing education', sub: 'Certified every year' }, { label: '+10 years of experience', sub: 'Madrid specialist' }, { label: 'Registered DGSFP agent', sub: 'Official agent register' }] },
  guarantee: { title: 'We review your quote', compact: 'Bring us any quote and we will review it with you among the options we can distribute, honestly.', body: 'Bring us any quote you have and we will compare the options we can distribute, so you can assess what best fits your situation.', cta: 'See how it works →', whatsapp: 'Hello, I would like to request a free comparison of my quote.' },
  finalCta: { title: 'Shall we talk about what concerns you?', body: 'A brief call is often the quickest way to clear things up. From there, we can work out which product makes sense for you, directly and professionally.', response: 'Average response time today: under 18 minutes', contact: 'Choose my cover with Rosa', whatsapp: 'Hello, I would like a no-obligation consultation to review which insurance suits me best.', imageAlt: 'Sebastián, a Valentín adviser specialising in life and health, combining personal care with technical expertise' },
  mascot: { imageAlt: 'Insurance adviser supporting a family in Madrid during a personal consultation', badge: '+10 years guiding people', kicker: 'Your point of support', title: 'Human guidance for important decisions', body: 'We designed this experience so you feel supported at every step. No jargon, no pressure and with an expert view of what really matters.', bullets: ['We organise priorities before you decide.', 'We put cover into clear language.', 'We highlight what is genuinely worth reviewing.', 'Support by WhatsApp or phone.'], cta: 'Explore how we help', whatsapp: 'Hello, I would like guidance to understand which insurance suits me best.' },
  reviews: { title: '', subtitle: '', all: 'See all on Google →', verified: 'verified Google reviews', previous: 'Previous review', next: 'Next review', review: 'View review' },
  zones: { label: 'Local cover', title: 'We serve the whole north-west of Madrid', linkPrefix: 'Insurance in ' },
};

export const homeContent: Record<HomeLocale, HomeContent> = { es, en };
export const getHomeContent = (locale: HomeLocale = 'es') => homeContent[locale];
