import Link from 'next/link';
import { Header } from '@/components/header';
import { Footer } from '@/components/footer';
import { Breadcrumbs } from '@/components/breadcrumbs';
import { StickyWhatsApp } from '@/components/sticky-whatsapp';
import { WhatsAppIcon } from '@/components/ui/whatsapp-icon';
import { buildWhatsAppHref } from '@/lib/products';
import { corporateContent, legalContent } from '@/lib/corporate-content';
import SchemaBreadcrumb from '@/components/seo/schema-breadcrumb';
import { GoogleReviewsCarousel } from '@/components/google-reviews-carousel';
import { googleReviews, googleReviewsSummary } from '@/lib/google-reviews';

export function LocalizedCorporatePage({ page, locale }: { page: 'how-we-help' | 'about-us'; locale: 'es' | 'en' }) {
  const c = corporateContent[page][locale];
  const path = page === 'how-we-help' ? '/how-we-help' : '/about-us';
  return <><SchemaBreadcrumb locale={locale} items={[{ name: locale === 'en' ? 'Home' : 'Inicio', item: `${locale === 'en' ? 'https://valentinproteccionintegral.com/en' : 'https://valentinproteccionintegral.com'}`, position: 1 }, { name: c.title, item: `https://valentinproteccionintegral.com${locale === 'en' ? `/en${path}` : page === 'how-we-help' ? '/como-te-ayudamos' : '/sobre-nosotros'}`, position: 2 }]} /><Header /><main className="pt-6 md:pt-8"><div className="container-shell"><Breadcrumbs items={[{ label: locale === 'en' ? 'Home' : 'Inicio', href: locale === 'en' ? '/en' : '/' }, { label: c.eyebrow }]} /></div><section className="section-pad"><div className="container-shell"><div className="soft-card overflow-hidden"><div className="p-8 md:p-14"><p className="kicker">{c.eyebrow}</p><h1 className="mt-4 max-w-5xl font-heading text-5xl font-bold leading-tight text-[var(--blue-deep)] md:text-7xl">{c.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-[var(--muted)] md:text-xl">{c.intro}</p></div></div></div></section>{c.sections.map((section) => <section key={section.title} className="section-pad pt-0"><div className="container-shell"><article className="soft-card p-8 md:p-12"><h2 className="section-title">{section.title}</h2><p className="section-copy mt-5 max-w-3xl">{section.body}</p>{section.bullets && <ul className="mt-7 grid gap-4 md:grid-cols-3">{section.bullets.map((item) => <li key={item} className="rounded-2xl border border-[var(--border)] bg-white p-5 text-sm leading-7 text-[var(--muted)]">{item}</li>)}</ul>}</article></div></section>)}<section className="section-pad pt-0"><div className="container-shell"><div className="rounded-[30px] bg-[var(--blue-deep)] px-7 py-12 text-center text-white md:px-12"><h2 className="font-heading text-4xl font-bold md:text-5xl">{c.cta}</h2><p className="mx-auto mt-5 max-w-2xl text-lg text-white/75">{locale === 'en' ? 'Ask us a question and we will help you review the available options.' : 'Cuéntanos tu caso y te ayudaremos a revisar las opciones disponibles.'}</p><a href={buildWhatsAppHref(locale === 'en' ? 'Hello, I would like guidance from Valentín Protección Integral.' : 'Hola, quiero orientación de Valentín Protección Integral.')} className="btn-whatsapp mt-8 inline-flex"><WhatsAppIcon className="h-4 w-4" />{locale === 'en' ? 'Chat on WhatsApp' : 'Hablar por WhatsApp'}</a></div></div></section></main><Footer /><StickyWhatsApp /></>;
}

export function LocalizedLegalPage({ page, locale }: { page: 'legal-notice' | 'privacy' | 'cookies'; locale: 'es' | 'en' }) {
  const c = legalContent[page];
  const esPath = page === 'legal-notice' ? '/aviso-legal' : `/${page}`;
  const enPath = `/en/${page}`;
  return <><SchemaBreadcrumb locale={locale} items={[{ name: locale === 'en' ? 'Home' : 'Inicio', item: locale === 'en' ? 'https://valentinproteccionintegral.com/en' : 'https://valentinproteccionintegral.com', position: 1 }, { name: c.title, item: `https://valentinproteccionintegral.com${locale === 'en' ? enPath : esPath}`, position: 2 }]} /><Header /><main className="section-pad pt-6 md:pt-10"><div className="container-shell"><Breadcrumbs items={[{ label: locale === 'en' ? 'Home' : 'Inicio', href: locale === 'en' ? '/en' : '/' }, { label: c.title }]} /><div className="soft-card p-8 md:p-12 prose prose-slate max-w-none"><p className="kicker">{locale === 'en' ? 'LEGAL' : 'LEGAL'}</p><h1 className="mt-3 section-title">{c.title}</h1><p className="section-copy mt-2">{locale === 'en' ? 'Last updated: April 2026' : 'Última actualización: abril de 2026'}</p>{c.sections.map((section) => <section key={section.title}><h2>{section.title}</h2>{section.paragraphs.map((p) => <p key={p}>{p}</p>)}{section.bullets && <ul>{section.bullets.map((b) => <li key={b}>{b}</li>)}</ul>}</section>)}</div></div></main><Footer /><StickyWhatsApp /></>;
}

export function LocalizedReviewsPage({ locale }: { locale: 'es' | 'en' }) {
  const en = locale === 'en';
  const title = en ? 'Real client reviews' : 'Opiniones reales';
  return <><SchemaBreadcrumb locale={locale} items={[{ name: en ? 'Home' : 'Inicio', item: `https://valentinproteccionintegral.com${en ? '/en' : ''}`, position: 1 }, { name: title, item: `https://valentinproteccionintegral.com${en ? '/en/reviews' : '/opiniones'}`, position: 2 }]} /><Header /><main className="pt-6 md:pt-8"><div className="container-shell"><Breadcrumbs items={[{ label: en ? 'Home' : 'Inicio', href: en ? '/en' : '/' }, { label: title }]} /></div><section className="section-pad"><div className="container-shell"><p className="kicker">{en ? 'REVIEWS' : 'OPINIONES'}</p><h1 className="mt-4 max-w-5xl font-heading text-5xl font-bold leading-tight text-[var(--blue-deep)] md:text-7xl">{en ? 'Trust is built by listening' : 'La confianza también se construye escuchando'}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-[var(--muted)]">{en ? 'These are experiences shared by people who have trusted our advice.' : 'Estas son experiencias compartidas por personas que han confiado en nuestro asesoramiento.'}</p><div className="mt-10 soft-card p-6 md:p-10"><p className="font-semibold text-[var(--muted)]">{en ? 'Google rating' : 'Valoración en Google'} · {googleReviewsSummary.rating.toFixed(1)} · {googleReviewsSummary.user_ratings_total} {en ? 'reviews' : 'opiniones'}</p><div className="mt-8"><GoogleReviewsCarousel reviews={googleReviews.filter((r) => r.text.trim())} {...googleReviewsSummary} /></div></div></div></section><section className="section-pad pt-0"><div className="container-shell"><div className="rounded-[30px] bg-[var(--blue-deep)] p-8 text-center text-white md:p-14"><h2 className="font-heading text-4xl font-bold md:text-5xl">{en ? 'Would you like guidance choosing your insurance?' : '¿Necesitas orientación para elegir tu seguro?'}</h2><a href={buildWhatsAppHref(en ? 'Hello, I need guidance choosing insurance.' : 'Hola, necesito orientación para elegir un seguro.')} className="btn-whatsapp mt-8 inline-flex"><WhatsAppIcon className="h-4 w-4" />{en ? 'Chat on WhatsApp' : 'Hablar por WhatsApp'}</a></div></div></section></main><Footer /><StickyWhatsApp /></>;
}
