export type LocalizedPage = {
  title: string;
  description: string;
  eyebrow: string;
  intro: string;
  sections: { title: string; body: string; bullets?: string[] }[];
  cta: string;
};

export const corporateContent: Record<'how-we-help' | 'about-us', { es: LocalizedPage; en: LocalizedPage }> = {
  'how-we-help': {
    es: { eyebrow: 'CÓMO TE AYUDAMOS', title: 'No somos un portal automático. Somos tu asesor.', description: 'Te asesoramos sobre la cobertura más adecuada y te acompañamos después de contratar.', intro: 'Escuchamos tu situación, te explicamos las coberturas con un lenguaje que se entiende y aterrizamos las opciones antes de decidir.', sections: [{ title: 'Escuchamos antes de recomendar', body: 'Queremos entender qué quieres proteger, en qué momento estás y cómo utilizas realmente tus seguros.', bullets: ['Escuchamos qué quieres proteger y en qué momento estás.', 'Ordenamos tus prioridades y tus dudas.', 'Te presentamos opciones que podemos distribuir.'] }, { title: 'Te ayudamos a comparar con criterio', body: 'No reducimos la decisión a una cuota mensual. Te explicamos las diferencias relevantes entre modalidades, límites y condiciones.', bullets: ['Separamos lo importante de la letra pequeña.', 'Comparamos coberturas y exclusiones.', 'Te decimos también cuando una opción ya es adecuada.'] }, { title: 'Seguimos a tu lado', body: 'El acompañamiento no termina cuando contratas. Puedes volver a consultarnos cuando necesites utilizar o revisar tu seguro.', bullets: ['Resolvemos tus dudas antes y después de contratar.', 'Te ayudamos a revisar cambios y renovaciones.', 'Mantenemos una atención cercana y directa.'] }], cta: 'Cuéntanos qué necesitas proteger.' },
    en: { eyebrow: 'HOW WE HELP', title: 'We are not an automated portal. We are your adviser.', description: 'We help you understand the cover that fits and stay by your side after you arrange it.', intro: 'We listen to your situation, explain cover in plain language and put the available options into context before you decide.', sections: [{ title: 'We listen before we recommend', body: 'We want to understand what you need to protect, where you are now and how you actually use insurance.', bullets: ['We listen to what you need to protect.', 'We organise your priorities and questions.', 'We present options we can distribute.'] }, { title: 'We help you compare with context', body: 'We do not reduce the decision to a monthly premium. We explain the relevant differences between plans, limits and conditions.', bullets: ['We separate the important points from the small print.', 'We compare cover and exclusions.', 'We will also tell you when an option is already suitable.'] }, { title: 'We stay by your side', body: 'Our support does not end when you arrange cover. You can come back to us whenever you need to use or review your insurance.', bullets: ['We answer questions before and after you buy.', 'We help review changes and renewals.', 'You receive direct, personal support.'] }], cta: 'Tell us what you need to protect.' },
  },
  'about-us': {
    es: { eyebrow: 'SOBRE NOSOTROS', title: 'Seguros explicados con claridad y acompañamiento real.', description: 'Conoce a las personas detrás de Valentín Protección Integral.', intro: 'Somos Rosa y Sebastián Valentín. Trabajamos desde Boadilla del Monte, Madrid, asesorando a familias, particulares y profesionales.', sections: [{ title: 'Una forma cercana de trabajar', body: 'Creemos que elegir un seguro debe empezar por entender tu situación, no por recibir una lista interminable de productos.' }, { title: 'Más de 10 años de experiencia', body: 'Nuestra experiencia comparando seguros de salud, vida, mascotas, dental, viaje, accidentes y decesos nos permite ayudarte con contexto.' }, { title: 'Mediación registrada', body: 'Valentín Protección Integral es una marca comercial de mediación de seguros. La actividad está inscrita en el Registro de Mediadores de la DGSFP.' }], cta: 'Conoce cómo podemos ayudarte.' },
    en: { eyebrow: 'ABOUT US', title: 'Insurance explained clearly, with real personal support.', description: 'Meet the people behind Valentín Protección Integral.', intro: 'We are Rosa and Sebastián Valentín. From Boadilla del Monte, Madrid, we advise families, individuals and professionals.', sections: [{ title: 'A personal way of working', body: 'We believe choosing insurance should start with understanding your situation, not with an endless list of products.' }, { title: 'More than 10 years of experience', body: 'Our experience comparing health, life, pet, dental, travel, accident and funeral insurance helps us give you useful context.' }, { title: 'Registered insurance mediation', body: 'Valentín Protección Integral is a commercial insurance mediation brand. The activity is registered with the DGSFP Mediators Register.' }], cta: 'Find out how we can help.' },
  },
};

export const legalContent: Record<'legal-notice' | 'privacy' | 'cookies', { title: string; description: string; sections: { title: string; paragraphs: string[]; bullets?: string[] }[] }> = {
  'legal-notice': { title: 'Legal notice', description: 'Legal notice and information about the owner of valentinproteccionintegral.com.', sections: [
    { title: '1. Owner identification', paragraphs: ['In compliance with Article 10 of Law 34/2002 of 11 July on Information Society Services and Electronic Commerce (LSSI-CE), the following information is provided:'], bullets: ['Owner: Rosa Valentín', 'NIF: 79234434D', 'DGSFP registration code: C012479234434D', 'Trade name: Valentín Protección Integral', 'Address: C. de los Reyes Católicos, 1, 28660 Boadilla del Monte, Madrid, Spain', 'Telephone: +34 603 448 765', 'Email: contacto@valentinproteccionintegral.com', 'Website: https://valentinproteccionintegral.com', 'DGSFP Register: registered in the Insurance and Reinsurance Mediators Register of the Dirección General de Seguros y Fondos de Pensiones (DGSFP).'] },
    { title: '2. Purpose and scope', paragraphs: ['This Legal Notice governs access to and use of valentinproteccionintegral.com. Access to the website implies express acceptance of these conditions.'] },
    { title: '3. Intellectual and industrial property', paragraphs: ['All website content, including text, photographs, graphics, images, logos, icons, source code and design, belongs to Rosa Valentín or its legitimate licensors and is protected by applicable intellectual and industrial property law.', 'Reproduction, distribution, public communication or transformation of any website element without the owner’s prior written authorisation is expressly prohibited.'] },
    { title: '4. Disclaimer', paragraphs: ['The owner is not liable for damage of any kind arising from access to or use of the website, including damage caused by viruses, service interruptions or technical failures beyond the owner’s control.', 'Website content is for guidance and does not constitute binding legal, tax or financial advice.'] },
    { title: '5. Links policy', paragraphs: ['The website may contain links to third-party websites. Valentín Protección Integral does not control or accept responsibility for their content, privacy policies or practices.'] },
    { title: '6. Applicable law and jurisdiction', paragraphs: ['This Legal Notice is governed by Spanish law. Any dispute shall be submitted to the courts and tribunals that have jurisdiction under the applicable rules.'] },
  ] },
  'privacy': { title: 'Privacy policy', description: 'Privacy policy and processing of personal data under the GDPR.', sections: [
    { title: '1. Data controller', paragraphs: ['Controller: Rosa Valentín (Valentín Protección Integral)', 'NIF: 79234434D', 'Activity: Insurance mediation — registered in the DGSFP Mediators Register (code C012479234434D)', 'Address: C. de los Reyes Católicos, 1, 28660 Boadilla del Monte, Madrid', 'Telephone: +34 603 448 765', 'Email: contacto@valentinproteccionintegral.com', 'Website: https://valentinproteccionintegral.com'] },
    { title: '2. Data collected and purposes', paragraphs: ['Through contact forms and landing pages, we collect the following data depending on the form used:'], bullets: ['Name and surname — to identify you and tailor the response.', 'Telephone — to contact you and advise you about the product or enquiry.', 'Email address — only where the form expressly requests it.', 'Product of interest and additional notes — to prepare useful guidance.', 'Source page URL and referrer — technical navigation data collected automatically.', 'UTM parameters — when you arrive from a campaign.', 'Date and time of submission — internal form record.'] },
    { title: '3. Retention period', paragraphs: ['Your data will be kept for as long as necessary to manage your enquiry and, where applicable, the resulting contractual relationship. After the relationship ends, data will be blocked for legally required periods and then securely deleted.'] },
    { title: '4. Your rights', paragraphs: ['You may exercise the following rights before the controller:'], bullets: ['Access: know what data we hold about you.', 'Rectification: correct inaccurate or incomplete data.', 'Erasure: request that your data be deleted.', 'Restriction: request that use of your data be suspended.', 'Portability: receive your data in a structured, readable format.', 'Objection: object to processing in certain circumstances.', 'Withdraw consent at any time, without affecting the lawfulness of prior processing.'], },
    { title: '5. Data security', paragraphs: ['We apply appropriate technical and organisational measures to protect personal data against unauthorised access, alteration, loss or disclosure.'] },
    { title: '6. Changes to this policy', paragraphs: ['We may update this policy when necessary. The version published on this page is the one currently applicable.'] },
  ] },
  'cookies': { title: 'Cookie policy', description: 'Information about the cookies used on valentinproteccionintegral.com.', sections: [
    { title: '1. What are cookies?', paragraphs: ['Cookies are small files stored on your device when you visit a website. They allow the website to remember information about your visit and improve its operation.'] },
    { title: '2. Cookies and services used by this website', paragraphs: ['This website uses necessary cookies to provide its basic functions. Analytics and marketing cookies are only installed when you accept or configure them through the cookie banner. Your choice is stored in the cookie-consent entry.'] },
    { title: '3. Legal basis', paragraphs: ['Necessary cookies are used because they are required for the website to operate. Analytics and marketing cookies are used only with your consent.'] },
    { title: '4. How to manage or delete cookies', paragraphs: ['You can accept, reject or configure optional cookies through the cookie banner. You can also manage cookies in your browser settings. Disabling necessary cookies may affect website functionality.'] },
    { title: '5. Updates to this policy', paragraphs: ['This policy may be updated when the cookies or services used by the website change.'] },
  ] },
};
