export type HealthForeignersLocale = 'es' | 'en';

export type HealthForeignersProductKey = 'students' | 'residents';

export const healthForeignersContent = {
  es: {
    topNotice: 'Revisamos que la modalidad se ajuste a los requisitos habituales de tu trámite antes de contratar', mobileNotice: 'Comprobamos tu caso antes de contratar',
    heroTitle: 'Seguro de salud para trámites de visado y residencia en España, según la modalidad', heroIntro: 'La modalidad debe encajar con tu trámite y sus condiciones.', heroAccent: 'Te ayudamos a revisar la opción antes de contratar.',
    timing: 'Preparamos la documentación con tiempo para tu cita; el plazo depende de la aseguradora y del producto', bullets: ['Modalidades para extranjería', 'Copagos y carencias según producto', 'Certificado sujeto a la aseguradora', 'Revisamos la modalidad y el trámite'], heroProof: 'Modalidades para visado, residencia y larga estancia', cta: 'Revisar mi caso', response: 'Plazo según la aseguradora y el caso', advisorLabel: 'Atención VPI', advisorRole: 'ASISA: mediación a través de Sebastián, agente exclusivo de ASISA',
    documentAlt: 'Certificado Oficial de Seguro de Salud', documentBadge: 'Según la aseguradora',
    productSelectorTitle: 'Elige el producto según tu situación',
    productSelector: [
      { key: 'students' as HealthForeignersProductKey, title: 'ASISA Health Students', copy: 'Para estudiantes internacionales y docentes que vienen a España por estudios. Duración de 2 a 12 meses, sin copagos ni carencias.', cta: 'Ver ASISA Health Students', href: '/seguros/salud-extranjeros/asisa-health-students' },
      { key: 'residents' as HealthForeignersProductKey, title: 'ASISA Health Residents', copy: 'Para personas extranjeras que necesitan seguro privado para un trámite de residencia o larga estancia cuando ese procedimiento lo exige. Duración anual, sin copagos ni carencias.', cta: 'Ver ASISA Health Residents', href: '/seguros/salud-extranjeros/asisa-health-residents' },
    ],
    productSelectorSecondary: '¿No sabes qué exige tu trámite? Consulta los requisitos de seguro para visados y residencia.', productSelectorSecondaryCta: 'Consultar requisitos de seguro', productSelectorSecondaryHref: '/visados/seguro-medico',
    profilesTitle: '¿Para quién es este seguro?', profilesIntro: 'Cada situación puede tener requisitos y plazos distintos; revisamos la modalidad y la documentación según tu trámite.', profiles: [{ title: 'Estudiante internacional', desc: 'Puede cubrir los requisitos habituales del visado de estudios según la modalidad. Comprobamos tu caso antes.' }, { title: 'Residencia o larga estancia en España', desc: 'Si tu trámite requiere seguro, revisamos la modalidad y la documentación que emite la aseguradora.' }, { title: 'Trabajador o emprendedor extranjero', desc: 'Coberturas según modalidad (copagos y carencias varían), compatible con distintas situaciones en España.' }],
    guaranteesTitle: 'Qué conviene comprobar antes de contratar', guarantees: ['La modalidad debe corresponder al trámite que describes', 'El certificado y sus fechas los emite la aseguradora', 'La administración o el consulado decide la aceptación'],
    processTitle: 'Ordena tu decisión en 3 pasos', process: [{ t: 'Cuéntanos el trámite', d: 'Indica si es para estudios, residencia, renovación o familia.' }, { t: 'Revisamos la modalidad', d: 'Comprobamos copagos, carencias, fechas y documentación.' }, { t: 'Recibes orientación clara', d: 'Te explicamos los siguientes pasos antes de contratar.' }], processCta: 'Revisar mi caso',
    errorKicker: '⚠️ Error frecuente', errorTitle: 'Un seguro inadecuado puede complicar tu expediente.', errorAccent: 'La modalidad importa.', errorCopy: 'Copagos, carencias, duración y documentación cambian según el producto. Antes de contratar, conviene comprobar que la modalidad y el certificado encajan con el trámite concreto.', errorLead: 'Te ayudamos a revisarlo.', errorDetail: 'La decisión final corresponde a la administración o al consulado; la póliza y el certificado fijan las condiciones del seguro.', errorCta: 'Revisar mi caso',
    statsTitle: 'Información clara para tu trámite', statsIntro: 'La página distingue productos y condiciones para que puedas preparar mejor la conversación con la aseguradora y, si corresponde, con tu asesor de extranjería.', stats: [{ num: 'Visado', label: 'Vías y trámites que podemos revisar' }, { num: 'ASISA', label: 'Productos con condiciones distintas' }, { num: '1', label: 'Decisión final de la autoridad competente' }],
    urgencyTitle: '¿Cuándo tienes la cita?', urgencyIntro: 'Te ayudamos igual — pero cuanto antes nos escribas, más tranquilo vas a estar.', urgent: { title: 'En menos de 7 días', desc: 'Es urgente — te damos prioridad inmediata' }, planned: { title: 'Tengo tiempo', desc: 'Perfecto — lo preparamos bien y sin prisas' }, write: 'Escribir ahora',
    specialistTitle: 'Orientación sobre seguros para trámites en España', specialistIntro: 'Te ayudamos a ordenar la parte aseguradora de tu caso.', specialistDetail: 'Revisamos las opciones y condiciones disponibles para el trámite que describes, sin sustituir la decisión de la autoridad competente.',
    easyTitle: 'Revisa lo importante antes de contratar', easy: ['Cuéntanos el trámite y las fechas relevantes', 'Te indicamos qué documentación emite la aseguradora', 'Consulta las condiciones de la modalidad elegida'],
    whyTitle: '¿Por qué puede necesitarse este seguro?', whyText: 'Según el trámite, la administración o el consulado puede exigir un seguro médico privado con determinadas coberturas y vigencia. Revisamos la parte aseguradora, pero no garantizamos la resolución del expediente.',
    identityKicker: 'Orientación humana', identityTitle: 'VPI te ayuda a entender la opción aseguradora.', identityIntro: 'Para productos ASISA, la mediación se realiza a través de Sebastián Sifontes Valentín, agente exclusivo de seguros de ASISA.', identityNote: 'La póliza y la aseguradora determinan las condiciones contractuales.', identityAlt: 'Rosa y Sebastián — Valentín Protección Integral',
    faqTitle: '❓ Preguntas frecuentes', faqSubtitle: 'Todo lo que necesitas saber para tu visado', faqs: [
      { q: '¿Cuándo puede requerirse un seguro médico privado?', a: 'Depende del procedimiento; algunos trámites de visado, residencia o larga estancia pueden exigir cobertura concreta. La aseguradora emite el certificado y la administración o el consulado decide si cumple los requisitos aplicables.' },
      { q: '¿El seguro tiene que ser obligatoriamente sin copagos?', a: 'Para muchos trámites se necesitan modalidades sin copagos. El manual de ASISA 2026 describe ASISA Health Students y ASISA Health Residents sin copagos; otras condiciones dependen del producto y la póliza. Revisamos el producto y el trámite concreto, y la decisión final corresponde a la administración o al consulado.' },
      { q: '¿Cuánto tarda en estar lista la póliza?', a: 'El plazo depende de la aseguradora, la modalidad y la información necesaria para emitirla. Te indicamos el estado y la documentación disponible para tu caso.' },
      { q: '¿Qué pasa si me rechazan el seguro en extranjería?', a: 'Las condiciones de devolución dependen del producto y de la póliza. Revisamos las condiciones aplicables antes de contratar; la decisión sobre el trámite corresponde a la administración o al consulado.' },
    ],
    finalTitle: 'Prepara la parte aseguradora de tu trámite', finalIntro: 'Revisa la modalidad, las fechas y la documentación antes de contratar.', finalCta: 'Revisar mi caso', fast: 'Te indicamos los siguientes pasos', complete: 'Condiciones según producto y aseguradora', footerMeta: 'Orientación de seguros con condiciones claras',
  },
  en: {
    topNotice: 'We check that the plan matches the usual requirements of your process before you buy', mobileNotice: 'We check your case before you buy',
    heroTitle: 'Health insurance for visa and residence processes in Spain, depending on the plan', heroIntro: 'The plan must fit your process and its conditions.', heroAccent: 'We help you review the option before you buy.',
    timing: 'We prepare the documentation for your appointment; timing depends on the insurer and product', bullets: ['Plans for immigration processes', 'Co-payments and waiting periods vary by product', 'Certificate subject to the insurer', 'We review the plan and process'], heroProof: 'Plans for visas, residence and long-stay processes', cta: 'Review my case', response: 'Timing depends on the insurer and case', advisorLabel: 'VPI support', advisorRole: 'ASISA: mediation through Sebastián, an ASISA exclusive insurance agent',
    documentAlt: 'Official health insurance certificate', documentBadge: 'Subject to the insurer',
    productSelectorTitle: 'Choose the product for your situation',
    productSelector: [
      { key: 'students' as HealthForeignersProductKey, title: 'ASISA Health Students', copy: 'For international students and teachers coming to Spain for studies. Duration from 2 to 12 months, with no co-payments or waiting periods.', cta: 'View ASISA Health Students', href: '/en/insurance/health/foreigners/asisa-health-students' },
      { key: 'residents' as HealthForeignersProductKey, title: 'ASISA Health Residents', copy: 'For foreigners who need private insurance for a residence or long-stay process when that procedure requires it. One-year duration, with no co-payments or waiting periods.', cta: 'View ASISA Health Residents', href: '/en/insurance/health/foreigners/asisa-health-residents' },
    ],
    productSelectorSecondary: 'Not sure what your process requires? Check the insurance requirements for visas and residence.', productSelectorSecondaryCta: 'Check insurance requirements', productSelectorSecondaryHref: '/en/visa-health-insurance',
    profilesTitle: 'Who is this insurance for?', profilesIntro: 'Different situations can involve different requirements and timing; we help review the plan and documents for your process.', profiles: [{ title: 'International student', desc: 'May meet the usual study visa requirements depending on the plan. We check your case first.' }, { title: 'Residence or long-stay process in Spain', desc: 'If your process requires insurance, we help review the plan and documents issued by the insurer.' }, { title: 'Foreign worker or entrepreneur', desc: 'Cover depends on the plan (co-payments and waiting periods vary) and can fit different situations in Spain.' }],
    guaranteesTitle: 'What to check before you buy', guarantees: ['The plan should match the process you describe', 'The insurer issues the certificate and its dates', 'The administration or consulate makes the final decision'],
    processTitle: 'Organise your decision in 3 steps', process: [{ t: 'Tell us about the process', d: 'Explain whether it is for studies, residence, renewal or family.' }, { t: 'We review the plan', d: 'We check co-payments, waiting periods, dates and documents.' }, { t: 'You receive clear guidance', d: 'We explain the next steps before you buy.' }], processCta: 'Review my case',
    errorKicker: '⚠️ Common mistake', errorTitle: 'The wrong plan can complicate an application.', errorAccent: 'The product matters.', errorCopy: 'Co-payments, waiting periods, duration and documents vary by product. Before you buy, check that the plan and certificate fit the specific process.', errorLead: 'We can help you review it.', errorDetail: 'The administration or consulate makes the final decision; the policy and certificate set the insurance conditions.', errorCta: 'Review my case',
    statsTitle: 'Clear information for your process', statsIntro: 'The page separates products and conditions so you can prepare a better conversation with the insurer and, where relevant, your immigration adviser.', stats: [{ num: 'Visa', label: 'Routes and processes we can review' }, { num: 'ASISA', label: 'Products with different conditions' }, { num: '1', label: 'Final decision by the competent authority' }],
    urgencyTitle: 'When is your appointment?', urgencyIntro: 'We can help either way — but the sooner you write, the more calmly we can prepare it.', urgent: { title: 'In less than 7 days', desc: 'Urgent — we will prioritise your case' }, planned: { title: 'I have time', desc: 'Great — we can prepare it carefully' }, write: 'Write now',
    specialistTitle: 'Insurance guidance for processes in Spain', specialistIntro: 'We help you organise the insurance side of your case.', specialistDetail: 'We review the available options and conditions for the process you describe, without replacing the decision of the competent authority.',
    easyTitle: 'Check the important points before you buy', easy: ['Tell us about the process and relevant dates', 'We explain which documents the insurer issues', 'Review the conditions of the selected plan'],
    whyTitle: 'Why might this insurance be needed?', whyText: 'Depending on the process, the administration or consulate may require private health insurance with specific cover and validity. We review the insurance side, but do not guarantee the outcome of an application.',
    identityKicker: 'Human guidance', identityTitle: 'VPI helps you understand the insurance option.', identityIntro: 'For ASISA products, insurance mediation is carried out through Sebastián Sifontes Valentín, an ASISA exclusive insurance agent.', identityNote: 'The policy and insurer determine the contractual conditions.', identityAlt: 'Rosa and Sebastián — Valentín Protección Integral',
    faqTitle: '❓ Frequently asked questions', faqSubtitle: 'Everything you need to know about your visa', faqs: [
      { q: 'When might private health insurance be required?', a: 'It depends on the process; some visa, residence or long-stay procedures may require specific cover. The insurer issues the certificate, and the administration or consulate decides whether it meets the applicable requirements.' },
      { q: 'Does the insurance have to be without co-payments?', a: 'Many processes require plans without co-payments. The ASISA 2026 manual describes ASISA Health Students and ASISA Health Residents without co-payments; other conditions depend on the product and policy. We review the product and process, while the final decision belongs to the administration or consulate.' },
      { q: 'How long does it take to issue the policy?', a: 'Timing depends on the insurer, product and information needed for issue. We explain the status and available documents for your case.' },
      { q: 'What happens if the insurance is rejected by immigration?', a: 'Refund conditions depend on the product and policy. We review the applicable conditions before you arrange cover; the authority or consulate decides the immigration procedure.' },
    ],
    finalTitle: 'Prepare the insurance side of your process', finalIntro: 'Review the plan, dates and documents before you buy.', finalCta: 'Review my case', fast: 'We explain the next steps', complete: 'Conditions depend on the product and insurer', footerMeta: 'Insurance guidance with clear conditions',
  },
} as const;
