import Image from 'next/image';
import { ArrowDown, ArrowRight } from 'lucide-react';
import { Header } from '@/components/header';
import { Footer } from '@/components/footer';
import { Breadcrumbs } from '@/components/breadcrumbs';
import { WhatsAppIcon } from '@/components/ui/whatsapp-icon';
import { buildWhatsAppHref } from '@/lib/products';
import { australiaContent, getAustraliaMetadata, type AustraliaContent, type AustraliaLocale } from './australia-content';
import styles from './australia.module.css';
const baseUrl = 'https://valentinproteccionintegral.com'; const imageRoot = '/images/internacional/australia'; const image = (name: string) => `${imageRoot}/${name}`;
export const metadata = getAustraliaMetadata('es');
function Eyebrow({ children }: { children: React.ReactNode }) { return <p className={styles.eyebrow}>{children}</p>; }
function Photo({ src, alt, className, sizes }: { src: string; alt: string; className: string; sizes: string }) { return <div className={className}><Image src={image(src)} alt={alt} fill sizes={sizes} /></div>; }
function RouteVisas({ number }: { number: string }) { if (number === '01') return <div className={styles.routeVisas}><strong className={styles.visaHero}>600</strong><span>601 · 651</span></div>; if (number === '02') return <div className={styles.routeVisas}><strong className={styles.visaHero}>500</strong><span>590 · 407</span></div>; if (number === '03') return <div className={`${styles.routeVisas} ${styles.visaWorking}`}><strong>417</strong><i>·</i><strong>462</strong></div>; if (number === '04') return <div className={`${styles.routeVisas} ${styles.visaSequence}`}><strong>482</strong><i aria-hidden="true" /><strong>186</strong></div>; if (number === '05') return <div className={`${styles.routeVisas} ${styles.visaSkilled}`}><strong>189</strong><strong>190</strong><strong>491<small>REGIONAL</small></strong></div>; return <div className={`${styles.routeVisas} ${styles.visaFamily}`}><span><strong>820</strong><i>→</i><strong>801</strong></span><span><strong>309</strong><i>→</i><strong>100</strong></span><strong>300</strong></div>; }
export function AustraliaPageView({ content: c, locale }: { content: AustraliaContent; locale: AustraliaLocale }) {
 const whatsappHref = buildWhatsAppHref(c.contact.whatsapp); const url = locale === 'en' ? `${baseUrl}/en/international/australia` : `${baseUrl}/internacional/australia`;
 const jsonLd = { '@context': 'https://schema.org', '@type': 'WebPage', inLanguage: locale, name: c.metadata.title, url, description: c.metadata.description, about: { '@type': 'Country', name: 'Australia' }, provider: { '@type': 'Organization', name: 'Valentín Protección Integral', url: baseUrl }, breadcrumb: { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: c.breadcrumb.home, item: `${baseUrl}${locale === 'en' ? '/en' : '/'}` }, { '@type': 'ListItem', position: 2, name: c.breadcrumb.international, item: `${baseUrl}${locale === 'en' ? '/en/international' : '/internacional'}` }, { '@type': 'ListItem', position: 3, name: c.breadcrumb.country, item: url }] }, mainEntity: { '@type': 'FAQPage', mainEntity: c.faq.items.map(f => ({ '@type': 'Question', name: f.question, acceptedAnswer: { '@type': 'Answer', text: f.answer } })) } };
 return <div className={styles.route}><Header/><main className={styles.page}>
 <section className={styles.hero} aria-labelledby="australia-title"><div className="container-shell"><div className={styles.breadcrumb}><Breadcrumbs items={[{label:c.breadcrumb.home,href:locale==='en'?'/en':'/'},{label:c.breadcrumb.international,href:locale==='en'?'/en/international':'/internacional'},{label:c.breadcrumb.country}]}/></div><div className={styles.heroComposition}><div className={styles.heroHeading}><div className={styles.heroIdentity}><Image src={image('bandera-australia.jpg')} alt={c.hero.flagAlt} width={400} height={206} className={styles.flag} priority/><span><strong>AUSTRALIA</strong><small>{c.hero.eyebrow}</small></span></div><div className={styles.heroIndex}>{c.hero.index.map((x,i)=><span key={x}>{i>0&&<i>↓</i>}{x}</span>)}</div><h1 id="australia-title"><span>{c.hero.title[0]}</span><span>{c.hero.title[1]}</span><em>{c.hero.title[2]}</em></h1><div className={styles.heroIntro}><p className={styles.heroLead}>{c.hero.lead}</p><p className={styles.heroDescription}>{c.hero.description}</p></div><div className={styles.heroRouteIndex} aria-label={c.hero.routeLabel}>{c.hero.route.map((x,i)=><span key={x}>{i>0&&<i>·</i>}{x}</span>)}</div><div className={styles.heroActions}><a href="#rutas" className={styles.primaryCta}>{c.hero.primary}<ArrowRight aria-hidden="true"/></a><a href={whatsappHref} className={styles.textCta}><WhatsAppIcon aria-hidden="true"/> {c.hero.secondary}<span>↗</span></a></div><span className={styles.heroChapter} aria-hidden="true">01</span></div><div className={styles.heroPhotoWrap}><div className={styles.heroPhotoFrame}><Photo src="australia-hero-sydney.webp" alt={c.hero.imageAlt} className={styles.heroPhoto} sizes="(max-width: 900px) 100vw, 60vw"/></div><div className={styles.photoLabel}><span>{c.hero.photoLabel}</span><small>33.8688° S · 151.2093° E</small></div></div></div></div></section>
 <section id="rutas" className={styles.routesSection} aria-labelledby="routes-title"><div className="container-shell"><div className={styles.sectionHeading}><div><Eyebrow>{c.routes.eyebrow}</Eyebrow><h2 id="routes-title">{c.routes.title}</h2></div><div><p>{c.routes.intro}</p><p className={styles.disclaimer}>{c.routes.disclaimer}</p></div></div><div className={styles.routeList}>{c.routes.items.map(r=><article className={styles.routeRow} data-episode={r.number} key={r.title}><div className={styles.routeMeta}><span className={styles.routeNumber}>{r.number}</span><h3>{r.title}</h3></div><RouteVisas number={r.number}/><p>{r.copy}</p></article>)}</div></div></section>
 <section className={styles.coverageSection} aria-labelledby="coverage-title"><div className="container-shell"><div className={styles.coverageMapLayer} aria-hidden="true"><Image src={image('australia-cartographic-overlay.svg')} alt="" width={1600} height={900} className={styles.decisionMap}/></div><div className={styles.coverageGrid}><div className={styles.coverageEditorial}><Eyebrow>{c.coverage.eyebrow}</Eyebrow><h2 id="coverage-title" className={styles.coverageTitle}><span>{c.coverage.title[0]}</span><span>{c.coverage.title[1]}</span><em>{c.coverage.title[2]}</em><em>{c.coverage.title[3]}</em></h2><p className={styles.coverageCopy}>{c.coverage.copy}</p><div className={styles.coverageCtaRow}><a href="#contacto" className={styles.lightCta}>{c.coverage.cta}<ArrowRight aria-hidden="true"/></a><span className={styles.coverageNote}>{c.coverage.note}</span></div></div><div className={styles.coveragePath}><p className={styles.coveragePathLabel}>{c.coverage.pathLabel}</p><div className={styles.coverageQuestions}>{c.coverage.questions.map((q,i)=><div className={styles.coverageStep} key={q.title}><strong>0{i+1}</strong><span className={styles.coverageDivider}/><div><h3>{q.title}</h3><p>{q.items}</p></div><span className={styles.coverageMarker}/></div>)}</div></div></div><div className={styles.coverageFooter}><span>{c.coverage.footer}</span></div></div></section>
 <section className={styles.studentSection} aria-labelledby="student-title"><div className="container-shell"><div className={styles.studentGrid}><Photo src="australia-estudiar-campus.webp" alt={c.student.imageAlt} className={styles.studentPhoto} sizes="(max-width: 900px) 100vw, 48vw"/><div className={styles.studentCopy}><span className={styles.giantNumber}>500</span><Eyebrow>{c.student.eyebrow}</Eyebrow><h2 id="student-title">{c.student.title[0]}<br/><em>{c.student.title[1]}</em></h2>{c.student.paragraphs.map(p=><p key={p}>{p}</p>)}<small>{c.student.note}</small></div></div></div></section>
 <section className={styles.workSection} aria-labelledby="work-title"><div className="container-shell"><div className={styles.workHeader}><div><Eyebrow>{c.work.eyebrow}</Eyebrow><h2 id="work-title">{c.work.title[0]}<br/><em>{c.work.title[1]}</em></h2></div><Photo src="australia-trabajo-commuters.webp" alt={c.work.imageAlt} className={styles.workPhoto} sizes="(max-width: 760px) 100vw, 30vw"/></div><div className={styles.workBranches}><div className={styles.branch}><span className={styles.branchLabel}>{c.work.branchA}</span><div className={styles.branchLine}><strong>482</strong><span>Skills in Demand</span></div><p>{c.work.temporary}</p><div className={styles.branchLine}><strong>186</strong><span>Employer Nomination Scheme</span></div><p>{c.work.permanent}</p></div><div className={styles.branch}><span className={styles.branchLabel}>{c.work.branchB}</span><div className={styles.skillNumbers}>{c.work.skills.map((s,i)=><div key={s.name}><strong>{['189','190','491'][i]}</strong><span>{s.name}</span><p>{s.copy}</p>{i===2&&<small>{c.work.regionalNote}</small>}</div>)}</div></div></div><div className={styles.graduateBridge}><span>{c.work.graduate}</span><strong>485</strong><div><b>Temporary Graduate</b><p>{c.work.graduateCopy}</p></div></div></div></section>
 <section className={styles.familySection} aria-labelledby="family-title"><div className="container-shell"><div className={styles.familyGrid}><div className={styles.familyHead}><Eyebrow>{c.family.eyebrow}</Eyebrow><h2 id="family-title">{c.family.title[0]}<br/>{c.family.title[1]}<br/><em>{c.family.title[2]}</em></h2></div><div className={styles.familyPhoto}><Image src="/images/internacional/joeyy-lee-H4A30mABrD4-unsplash.jpg" alt={c.family.imageAlt} fill sizes="(max-width: 800px) 100vw, 40vw" style={{objectFit:'cover'}}/></div><div className={styles.familyBody}><div className={styles.familyRoutes}>{c.family.routes.map((r,i)=><>{i>0&&<i key={`${r.number}-arrow`}>↓</i>}<div key={r.number}><strong>{r.number}</strong><span>{r.name}</span></div></>)}</div><p className={styles.familyNote}>{c.family.note}</p></div></div></div></section>
 <section className={styles.migrationSection} aria-labelledby="migration-title"><div className="container-shell"><Eyebrow>{c.migration.eyebrow}</Eyebrow><h2 id="migration-title">{c.migration.title[0]}<br/><em>{c.migration.title[1]}</em></h2><div className={styles.migrationGrid}>{c.migration.paragraphs.map(p=><p key={p}>{p}</p>)}</div><a href="#contacto" className={styles.primaryCta}>{c.migration.cta}<ArrowRight aria-hidden="true"/></a></div></section>
 <section className={styles.lifeSection} aria-labelledby="life-title"><div className="container-shell"><Eyebrow>{c.life.eyebrow}</Eyebrow><h2 id="life-title">{c.life.title[0]}<br/><em>{c.life.title[1]}</em></h2><div className={styles.lifeGrid}>{c.life.items.map((item,i)=><figure className={[styles.lifeMove,styles.lifeCity,styles.lifeBreathe][i]} key={item.label}><Photo src={['australia-moverte-ferry.webp','australia-ciudad-melbourne.webp','australia-respirar-bondi.webp'][i]} alt={item.imageAlt} className={styles.lifePhoto} sizes="(max-width: 760px) 100vw, 48vw"/><figcaption><b>{item.label}</b><span>{item.copy}</span></figcaption></figure>)}</div></div></section>
 <section className={styles.processSection} aria-labelledby="process-title"><div className="container-shell"><Eyebrow>{c.process.eyebrow}</Eyebrow><h2 id="process-title">{c.process.title[0]}<br/><em>{c.process.title[1]}</em></h2><div className={styles.processGrid}>{c.process.items.map(item=><div key={item.number} className={styles.processStep}><span>{item.number}</span><h3>{item.title}</h3><p>{item.copy}</p></div>)}</div></div></section>
 <section className={styles.faqSection} aria-labelledby="faq-title"><div className="container-shell"><Eyebrow>{c.faq.eyebrow}</Eyebrow><h2 id="faq-title">{c.faq.title[0]}<br/><em>{c.faq.title[1]}</em></h2><div className={styles.faqList}>{c.faq.items.map(f=><details key={f.question}><summary>{f.question}<ArrowDown aria-hidden="true"/></summary><p>{f.answer}</p></details>)}</div><p className={styles.sourceNote}>{c.faq.source}</p></div></section>
 <section id="contacto" className={styles.contactSection} aria-labelledby="contact-title"><div className="container-shell"><Image src={image('bandera-australia.jpg')} alt={c.contact.imageAlt} width={400} height={206} className={styles.contactFlag}/><Eyebrow>{c.contact.eyebrow}</Eyebrow><h2 id="contact-title">{c.contact.title[0]}<br/><em>{c.contact.title[1]}</em></h2><p>{c.contact.copy}</p><div className={styles.contactActions}><a href="#rutas" className={styles.primaryCta}>{c.contact.primary}<ArrowRight aria-hidden="true"/></a><a href={whatsappHref} className={styles.textCta}><WhatsAppIcon aria-hidden="true"/> {c.contact.secondary}<span>↗</span></a></div></div></section>
 </main><Footer/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/></div>;
}
export default function AustraliaPage(){return <AustraliaPageView content={australiaContent.es} locale="es"/>;}
