import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { ProductSubpagePageView } from '@/app/seguros/[slug]/[subslug]/page';
import { products, subpages } from '@/lib/products';
import { getLocalizedSubpage, getProductAlternateLanguages, resolveProductSlug, localizedSubpagePath } from '@/lib/product-locales';
export const dynamic = 'force-dynamic';
export function generateStaticParams() { return subpages.flatMap((s) => [{ slug: s.parent, subslug: s.slug }]); }
export async function generateMetadata({ params }: { params: Promise<{ locale:string; slug:string; subslug:string }> }): Promise<Metadata> { const {locale,slug,subslug}=await params; const parent=resolveProductSlug(slug); const s=subpages.find((x)=>x.parent===parent && (x.slug===subslug || localizedSubpagePath(parent,x.slug,'en').endsWith(`/${subslug}`))); if (!s || locale!=='en') return {}; const e=getLocalizedSubpage(s,'en'); const url=`https://valentinproteccionintegral.com${localizedSubpagePath(parent,s.slug,'en')}`; const esUrl=`https://valentinproteccionintegral.com/seguros/${parent}/${s.slug}`; return {title:e.metaTitle,description:e.metaDescription,alternates:{canonical:url,languages:getProductAlternateLanguages(`${parent}/${s.slug}`,esUrl,url)},openGraph:{title:e.metaTitle,description:e.metaDescription,url,locale:'en_GB',type:'website'}}; }
export default async function EnglishProductSubpageRoute({ params }: { params: Promise<{ locale:string; slug:string; subslug:string }> }) { const {locale,slug,subslug}=await params; if(locale!=='en') notFound(); const parent=resolveProductSlug(slug); const s=subpages.find((x)=>x.parent===parent && (x.slug===subslug || localizedSubpagePath(parent,x.slug,'en').endsWith(`/${subslug}`))); if(!s) notFound(); return <ProductSubpagePageView parent={parent} subpage={s} locale="en" />; }
